name: masakini
description: Aplikasi Resep Masakan Bilingual

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Supabase untuk backend
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0 # Environment variables

  # Authentication & Cloud Services
  google_sign_in: ^6.1.6

  # UI & Image Handling
  image_picker: ^1.0.4 # Untuk foto resep/profil

  # State Management
  provider: ^6.1.1

  # Localization
  intl: ^0.20.2 # Bilingual
  flutter_localizations:
    sdk: flutter

  # Additional Features
  share_plus: ^7.2.1 # Share ke social media
  flutter_rating_bar: ^4.0.1 # Rating stars
  flutter_screenutil: ^5.9.0 # Responsive dari Figma (ukuran UI)
  uuid: ^4.5.1 # Generate unique IDs
  # Tambah jika Figma punya SVG: flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  # tambahkan ini jika belum ada
